import { tr } from "motion/react-client"

const heroSectionSlideData = [
    {
        imgSrc: '/heroSection-1.webp',
        alt: 'Hero Section Image 1',
        title: 'Blanc Musk',
        desc: 'A delicate blend of clean skin accords and warm white musk that settles softly into the senses. Minimal yet deeply intimate, Blanc Musk feels effortless, airy, and timeless — the kind of scent that lingers quietly in memory long after you leave the room.',
    },
    {
        imgSrc: '/heroSection-2.webp',
        alt: 'Hero Section Image 2',
        title: 'Gris Santal',
        desc: 'Smooth sandalwood layered with smoky grey vetiver creates a scent that feels grounded, calm, and quietly powerful. Gris Santal carries an understated elegance, balancing warmth and depth with a refined earthy character made for moments of still confidence.',
    },
    {
        imgSrc: '/heroSection-3.webp',
        alt: 'Hero Section Image 3',
        title: 'Peau Douce',
        desc: 'Soft cashmere notes wrapped in velvety musk create a fragrance that feels like a second skin. Peau Douce is comforting, warm, and deeply personal — subtle enough for everyday wear yet memorable enough to leave a lasting emotional impression.',
    },
    {
        imgSrc: '/heroSection-4.webp',
        alt: 'Hero Section Image 4',
        title: 'Lumière Noire',
        desc: 'Bright bergamot opens into the mysterious richness of oud, creating a contrast between light and shadow that feels hypnotic and cinematic. Lumière Noire transforms throughout the day, revealing smoky, resinous layers that evoke late evenings and quiet luxury.',
    },
    {
        imgSrc: '/heroSection-5.webp',
        alt: 'Hero Section Image 5',
        title: 'Eau Sauvage',
        desc: 'Fresh citrus bursts over rugged woods and aromatic herbs, capturing the feeling of cool wind moving through untouched landscapes. Eau Sauvage is vibrant, adventurous, and energizing — a scent inspired by freedom, open skies, and raw natural beauty.',
    },
]

export { heroSectionSlideData }

const products = [
    {
        id: 1,
        imgSrc: '/sauvage.webp',
        alt: 'Sauvage by Dior',
        name: 'Sauvage',
        brand: 'Dior',
        price: 12500,
        originalPrice: 15000,
        onSale: true,
        category: 'Men',
        size: '100ml',
    },
    {
        id: 2,
        imgSrc: '/sauvage.webp',
        alt: 'Bleu de Chanel',
        name: 'Bleu de Chanel',
        brand: 'Chanel',
        price: 18000,
        originalPrice: 18000,
        onSale: false,
        category: 'Men',
        size: '100ml',
    },
    {
        id: 3,
        imgSrc: '/sauvage.webp',
        alt: 'Black Opium by YSL',
        name: 'Black Opium',
        brand: 'Yves Saint Laurent',
        price: 9500,
        originalPrice: 14000,
        onSale: true,
        category: 'Women',
        size: '90ml',
    },
    {
        id: 4,
        imgSrc: '/sauvage.webp',
        alt: 'La Vie Est Belle by Lancome',
        name: 'La Vie Est Belle',
        brand: 'Lancôme',
        price: 11000,
        originalPrice: 13500,
        onSale: true,
        category: 'Women',
        size: '75ml',
    },
    {
        id: 5,
        imgSrc: '/sauvage.webp',
        alt: 'Acqua di Gio by Armani',
        name: 'Acqua di Giò',
        brand: 'Giorgio Armani',
        price: 13000,
        originalPrice: 13000,
        onSale: false,
        category: 'Men',
        size: '100ml',
    },
    {
        id: 6,
        imgSrc: '/sauvage.webp',
        alt: 'Chance Eau Tendre by Chanel',
        name: 'Chance Eau Tendre',
        brand: 'Chanel',
        price: 8500,
        originalPrice: 16000,
        onSale: true,
        category: 'Women',
        size: '50ml',
    },
    {
        id: 7,
        imgSrc: '/sauvage.webp',
        alt: 'Oud Wood by Tom Ford',
        name: 'Oud Wood',
        brand: 'Tom Ford',
        price: 32000,
        originalPrice: 32000,
        onSale: false,
        category: 'Unisex',
        size: '50ml',
    },
    {
        id: 8,
        imgSrc: '/sauvage.webp',
        alt: 'Flowerbomb by Viktor & Rolf',
        name: 'Flowerbomb',
        brand: 'Viktor & Rolf',
        price: 7800,
        originalPrice: 12000,
        onSale: true,
        category: 'Women',
        size: '50ml',
    },
    {
        id: 9,
        imgSrc: '/sauvage.webp',
        alt: 'Aventus by Creed',
        name: 'Aventus',
        brand: 'Creed',
        price: 45000,
        originalPrice: 45000,
        onSale: false,
        category: 'Men',
        size: '100ml',
    },
    {
        id: 10,
        imgSrc: '/sauvage.webp',
        alt: 'Libre by YSL',
        name: 'Libre',
        brand: 'Yves Saint Laurent',
        price: 10500,
        originalPrice: 14500,
        onSale: true,
        category: 'Women',
        size: '90ml',
    },
]

export { products }